# Generated by Django 3.1.7 on 2021-05-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionplanning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacityscheduling',
            options={},
        ),
        migrations.AlterModelOptions(
            name='crp',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mrp',
            options={},
        ),
        migrations.AlterField(
            model_name='capacityscheduling',
            name='BalMcOrHour',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='BAL MC/RES HOUR'),
        ),
    ]
