# Generated by Django 3.1.7 on 2021-05-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionplanning', '0002_auto_20210508_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacityscheduling',
            name='BalMcOrHour',
            field=models.FloatField(blank=True, null=True, verbose_name='BAL MC/RES HOUR'),
        ),
    ]
