# Generated by Django 3.1.7 on 2021-05-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionplanning', '0008_auto_20210517_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionandapproval',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.RenameField(
            model_name='productcenter',
            old_name='final_0utput',
            new_name='final_output',
        ),
        migrations.AlterField(
            model_name='submissionandapproval',
            name='pland_subm_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pland Subm Date'),
        ),
        migrations.AlterField(
            model_name='submissionandapproval',
            name='submitted_date',
            field=models.DateField(blank=True, null=True, verbose_name='Submitted Date'),
        ),
    ]
