# Generated by Django 3.1.7 on 2021-05-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionplanning', '0009_auto_20210517_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationsequence',
            name='componentsuses',
        ),
        migrations.AddField(
            model_name='operationsequence',
            name='componentsuser',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Components user'),
        ),
    ]
