# Generated by Django 3.1.7 on 2021-05-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productionplanning', '0010_auto_20210517_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcenter',
            name='final_output',
            field=models.CharField(choices=[('', '---Select---'), ('M/C Set-Up', 'M/C Set-Up'), ('Greige Fabric', 'Greige Fabric'), ('RTD Batch', 'RTD Batch'), ('Dyed Fabric', 'Dyed Fabric'), ('AOP Fabric', 'AOP Fabric'), ('Finished Fabric', 'Finished Fabric'), ('Semi-Fin Product', 'Semi-Fin Product'), ('Other', 'Other')], max_length=32, verbose_name='Final Output'),
        ),
    ]
